### ISSUE TITLE
Ignored `port` from config in Windows

### ISSUE THREAD

**Issue by inaneverb** [jackc/tern#38] opened 2021-09-21 18:39 UTC
Windows 11 Pro N, 21H2
Tern: 1.12.5
PostgreSQL 13.4 in Docker for Windows.
Docker uses WSL2 as a backend. 
WSL OS: Fedora Server 34.
Port mapping in docker enabled: 5432 container -> 5431 host.

I built two different binaries: for unix:amd/64, windows:amd/64.
If I run an unix's binary it's OK. It can connect, do necessary work, etc. 
If I run window's binary I getting an error "Failed to connect" and I see a default pg port: 5432, not those which is specified in config.

---

Output:
```bash
iyuryevich@ElevenStation ~/Development/___/migrations/ru (master+*?) $ tern.exe status
Unable to connect to PostgreSQL:
  failed to connect to `host=127.0.0.1 user=test1 database=test_dev_01`: dial error (dial tcp 127.0.0.1:5432: connectex: No connection could be made because the target machine actively refused it.)
iyuryevich@ElevenStation ~/Development/___/migrations/ru (master+*?) $ tern status
status:   up to date
version:  4 of 4
host:     127.0.0.1
database: test_dev_01
iyuryevich@ElevenStation ~/Development/___/migrations/ru (master+*?) $ tern.exe version
tern v1.12.5
iyuryevich@ElevenStation ~/Development/___/migrations/ru (master+*?) $ tern version
tern v1.12.5
iyuryevich@ElevenStation ~/Development/___/migrations/ru (master+*?) $
```

---

`tern.conf`

```ini
[database]
host = 127.0.0.1
port = 5431
database = test_dev_01
user = test1
password = root
version_table = schema_version
```

**Comment by jackc** [comment] 2021-09-25 14:37
That's very strange. I don't have convenient access to test this on Windows, but I don't see what could be different between *nix and Windows here.

**Comment by lucasgpalves** [comment] 2024-08-06 00:38
It seems that the problem you are experiencing is due to the port setting in your tern configuration. The error indicates that the connection is trying to use the default port (5432), ignoring the specified port (5431). This can occur for various reasons, including the way environment variables are interpreted or how the connection string is configured.

```ini
[database]
user=test1 
password=root
conn_string = host=127.0.0.1 port=5431 dbname=test_dev_01  connect_timeout=10
```

**Comment by smainz** [comment] 2024-09-05 08:23
I can confirm that bug (currently on Windows): If **sslmode is not set**, tern does not pick up port in tern.conf or command line 
If you set `sslmode = prefer` tern picks up the port both in tern.conf or on the command line.

**Comment by smainz** [comment] 2024-09-15 17:58
@jackc I think I found the root cause for this error.

The port is properly read from config file or cli argument, but when a connectionis created here:

https://github.com/jackc/tern/blob/160bdb3adcc37d446f54a2a0656860970262067b/main.go#L1062-L1063

a fallback connection is created as well.

In the next steps some config arguments are overwritten with args from file or args from cli

https://github.com/jackc/tern/blob/160bdb3adcc37d446f54a2a0656860970262067b/main.go#L1082

and

https://github.com/jackc/tern/blob/160bdb3adcc37d446f54a2a0656860970262067b/main.go#L1098

The config is still correct, but the port is not set in Config.Fallbacks[0]:
![image](https://github.com/user-attachments/assets/d9b37c1b-0f74-491f-8cb7-1aa531f25678)

If `pgx.ConnectConfig()` is not able to connect to the database  with the config parameters (it looks like on Windows (did not test Linux) empty sslmode is invalid) it uses the fallback. 
The result is an error message containing the port from the fallback, as the fallback points to the wrong port.

Incase `c.SslMode` is set this problem does not show up, as the `PG_*` env vars are set:

https://github.com/jackc/tern/blob/160bdb3adcc37d446f54a2a0656860970262067b/main.go#L155-L175

and the Fallbacks are copied to the config. 

To solve this, I see these options:

1. Set a default value for sslmode (e.g. prefered) in main.go 362
   https://github.com/jackc/tern/blob/160bdb3adcc37d446f54a2a0656860970262067b/main.go#L362
2. disallow empty sslmode here:
   https://github.com/jackc/tern/blob/160bdb3adcc37d446f54a2a0656860970262067b/main.go#L131-L132
  to show an error message about invalid sslmode
3. Add "" as valid sslmode here:
   https://github.com/jackc/tern/blob/160bdb3adcc37d446f54a2a0656860970262067b/main.go#L155-L156
4. Extract port and host from file, env and cli before calling pgx.Connect("") ans set env vars `PG_*`here:
   https://github.com/jackc/tern/blob/160bdb3adcc37d446f54a2a0656860970262067b/main.go#L1062
5. copy port to the Falbacks before trying to connect 


I consider a rewrite of LoadConfig to first load the arguments, merge them and then create the config the cleanest approach, but the one with the most changes.

Do you have an opinion about which options is best? 

I would prepare the PR.

**Comment by jackc** [comment] 2024-09-21 13:05
Thanks for the in-depth analysis.

> I consider a rewrite of LoadConfig to first load the arguments, merge them and then create the config the cleanest approach, but the one with the most changes.

I think this is the best approach. Take a look at #107.

**Comment by smainz** [comment] 2024-09-25 09:45
Thanks a lot , #107 looks like it does what i need.

Do you need my help on anything?

**Comment by jackc** [comment] 2024-09-26 22:10
> Thanks a lot , https://github.com/jackc/tern/pull/107 looks like it does what i need.

Just merged it into master. 

> Do you need my help on anything?

If you can test master and make sure it works that would help.

**Comment by smainz** [comment] 2024-09-28 10:18
I can confirm this works as expected:
- with config file it picks up the port from the file
- with cli argument it picks up the port from the command line
- with config file and cli argument the cli argument overrides the port in the config file
- with env var PGPORT set it picks up the port from PGPORT
- with env var PGPORT set and cli argument the cli argument overrides the env var

I am unsure about this:
- with PGPORT set and config file the config file overrides the env var.
  Usually I'd expect it the other way round, but I am not sure about conventions in postgres tooling.

**Comment by jackc** [comment] 2024-09-28 14:34
I'm not sure either. My expectation is that the priority is CLI arg, config file, then envvar. But I'm not sure where that idea came from. It may or may not be standard expectation.

**Comment by smainz** [comment] 2024-09-28 14:42
My expectation is different (highest priority first): 
1. cli arg
2. env var
3. config file

The rational is: The more ad-hoc the parameter can be set / the more ephermal it is the higher the priority. 
For one-off use cases I would not edit the config, but just use cli arg or if I need to call `tern`twice use an env var.

But expectations may be different. Let's keep it the way it is, usually I use config file and cli args,so env vars is an edge case for me.

Thanks for your effort.

**Comment by jackc** [comment] 2024-09-29 13:47
👍 

Just tagged v2.2.2 with this fix.

**Closed by jackc** 2024-09-29 13:47 UTC
